# Generated by Django 3.2.7 on 2021-09-22 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_auto_20210922_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ['-published'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
    ]
