# Generated by Django 3.2.7 on 2021-10-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_alter_bb_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
